const courses = [
    {id: 1 , name: 'Social Networking and Cybersecurity Best Practices', description:'A hands-on study of current social networking applications and approaches to protect against cyber attacks and enhance personal cybersecurity.', code: 'CMIS 100', credit: 2, department_code: 'CS', semester_offered: 'Fall', registered_students: [1,9,7,11,14,23,28,30]},
    {id: 2 , name: 'Introductory Programming', description:'A study of structured and object-oriented programming using the Java language.', code: 'CMIS 200', credit: 2, department_code: 'CS', semester_offered: 'Summer', registered_students: [9,7,2,5,12,15,23,29]},
    {id: 3 , name: 'Relational Database Concepts and Applications', description:'A study of the functions, underlying concepts, and applications of enterprise relational database management systems (RDBMS) in a business environment.', code: 'CMIT 111', credit: 2, department_code: 'CS', semester_offered: 'Fall', registered_students: [9,17,18,22,27]},
    {id: 4 , name: 'Fundamentals of Networking', description:'An introduction to networking technologies for local area networks, wide area networks, and wireless networks.', code: 'CMIT 112', credit: 2, department_code: 'CS', semester_offered: 'Fall',registered_students: [1,2,11,15,18,22,26,29,30]},
    {id: 5 , name: 'Network Security ', description:'A study of the fundamental concepts of computer security and its implementation.', code: 'CMIT 113', credit: 2, department_code: 'CS', semester_offered: 'Spring', registered_students: [3,6,10,13,15,24]},
    {id: 6 , name: 'Linux System Administration', description:'A study of the Linux operating system. ', code: 'CMIT 114', credit: 2, department_code: 'CS', semester_offered: 'Summer',registered_students: [16,18,19,24,27,28]},
    {id: 7 , name: 'Digital Forensics Analysis and Application', description:'A project-driven study of the digital forensic evaluation process.', code: 'CMIT 115', credit: 2, department_code: 'CS', semester_offered: 'Spring' ,registered_students: [7,6,10,16,19,25]},
    {id: 8 , name: 'Advanced Information Systems Security', description:'A comprehensive study of information systems security to enhance organizational security.', code: 'CMIT 116', credit: 4, department_code: 'CS', semester_offered: 'Fall', registered_students: [2,3,4,12,16,21]},
    {id: 9 , name: 'Mobile Forensics', code: 'CMIT 117', description:'A project-driven study of mobile devices from a forensic perspective.', credit: 2, department_code: 'CS', semester_offered: 'Spring' ,registered_students: [5,8,13,19,20,24,30]},
    {id: 10 , name: 'Secure Programming in the Cloud', description:'A hands-on study of programming secure applications in the cloud.', code: 'CMIS 300', credit: 3, department_code: 'SDEV', semester_offered: 'Fall' ,registered_students: [1,5,10,14,25,27]},
    {id: 11 , name: 'Mitigating Software Vulnerabilities', description:'An in-depth analysis and evaluation of the mitigation of software vulnerabilities.', code: 'CMIS 400', credit: 4, department_code: 'SDEV', semester_offered: 'Summer' ,registered_students: [4,8,11,14,21,25,26]},
    {id: 12 , name: 'Software Security Testing', description:' A hands-on study of exploits, attacks, and techniques used to penetrate application security defenses and strategies for mitigating such attacks.', code: 'CMIS 500', credit: 2, department_code: 'SDEV', semester_offered: 'Fall',registered_students: [3,4,12,17,20,26,28]}
];

module.exports = courses;