const students = [
    {id: 1,first_name: "James",last_name: "Holden",department_code: "CS",dob: "1982-12-06",gender: "M"},
    {id: 2,first_name: "Fred",last_name: "Johnson",department_code: "CS",dob: "1980-01-21",gender: "M"},
    {id: 3,first_name: "Naomin",last_name: "Nagata",department_code: "SDEV",dob: "1910-09-13",gender: "F"},
    {id: 4,first_name: "Amos",last_name: "Burton",department_code: "SDEV",dob: "1984-07-01",gender: "M"},
    {id: 5,first_name: "Chrisjen",last_name: "Avasarala",department_code: "CS",dob: "1989-12-09",gender: "F"},
    {id: 6,first_name: "Sansa",last_name: "Stark",department_code: "CS",dob: "1982-1-06",gender: "F"},
    {id: 7,first_name: "Arya",last_name: "Stark",department_code: "CS",dob: "1987-05-21",gender: "F"},
    {id: 8,first_name: "Bran",last_name: "Stark",department_code: "SDEV",dob: "1990-08-13",gender: "M"},
    {id: 9,first_name: "Brienne",last_name: "Tarth",department_code: "SDEV",dob: "1984-06-01",gender: "F"},
    {id: 10,first_name: "Samwell",last_name: "Tarley",department_code: "SDEV",dob: "1989-10-09",gender: "M"},
    {id: 11,first_name: "Theon",last_name: "Greyjoy",department_code: "CS",dob: "1982-12-06",gender: "M"},
    {id: 12,first_name: "Tyrion",last_name: "Lanaster",department_code: "CS",dob: "1987-08-07",gender: "M"},
    {id: 13,first_name: "Richard",last_name: "Hendricks",department_code: "SDEV",dob: "1992-06-12",gender: "M"},
    {id: 14,first_name: "Dinesh",last_name: "Kumail",department_code: "SDEV",dob: "1984-04-09",gender: "M"},
    {id: 15,first_name: "Erlich",last_name: "Bachman",department_code: "CS",dob: "1989-02-20",gender: "M"},
    {id: 16,first_name: "Gilfoyle",last_name: "Starr",department_code: "CS",dob: "1982-11-19",gender: "M"},
    {id: 17,first_name: "Jered",last_name: "Dunn",department_code: "CS",dob: "1987-09-19",gender: "M"},
    {id: 18,first_name: "Big",last_name: "Head",department_code: "SDEV",dob: "1993-09-13",gender: "M"},
    {id: 19,first_name: "Pi",last_name: "Patel",department_code: "SDEV",dob: "1984-12-01",gender: "M"},
    {id: 20,first_name: "Dwight",last_name: "Shrute",department_code: "CS",dob: "1989-02-19",gender: "M"},
    {id: 21,first_name: "Pam",last_name: "Beesly",department_code: "CS",dob: "1982-03-04",gender: "F"},
    {id: 22,first_name: "Michael",last_name: "Scott",department_code: "CS",dob: "1987-06-28",gender: "M"},
    {id: 23,first_name: "Darlene",last_name: "Alderson",department_code: "SDEV",dob: "1987-09-13",gender: "F"},
    {id: 24,first_name: "Elliot",last_name: "Alderson",department_code: "SDEV",dob: "1984-09-16",gender: "M"},
    {id: 25,first_name: "Imogen",last_name: "Heap",department_code: "CS",dob: "1989-12-09",gender: "F"},
    {id: 26,first_name: "Tash",last_name: "Sultana",department_code: "CS",dob: "1982-12-28",gender: "F"},
    {id: 27,first_name: "Thomas",last_name: "Shelby",department_code: "CS",dob: "1987-01-21",gender: "M"},
    {id: 28,first_name: "Aurora",last_name: "Aksnes",department_code: "SDEV",dob: "2000-09-13",gender: "F"},
    {id: 29,first_name: "Alfie",last_name: "Solomons",department_code: "SDEV",dob: "1997-07-01",gender: "M"},
    {id: 30,first_name: "Dolores",last_name: "Abernathy",department_code: "CS",dob: "1990-02-09",gender: "F"}
];
module.exports = students;